apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: federation
  namespace: simple-app
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  pathname: 'https://github.com/ansonmez/rhacmgitopslab.git'
  type: GitHub
